Fpgacount2config
swarm64/s64da-netdata-plugin pull request #1
Opened 2019-09-12 09:42 UTC by afswarm

2019-09-12 09:46 UTC, sdressler requested changes
Few minor things...

2019-09-12 09:46 UTC, sdressler commented on fpga.chart.py
> +# Description: example netdata python.d module
Can you fill in lines 2, 3 and 4?

2019-09-12 09:46 UTC, sdressler commented on fpga.chart.py
> +TEMP_DEFINITION = {
Please remove

2019-10-02 13:51 UTC, afswarm commented on fpga.chart.py
> +TEMP_DEFINITION = {
remove TEMP_DEFINITION?

2019-10-02 13:54 UTC, afswarm commented on fpga.chart.py
> +# Description: example netdata python.d module
done

2019-10-02 14:31 UTC, sdressler reviewed
Sorry, this question just occurred to me: what happens when TEMP cannot be collected, i.e. will it die or just report "0"?

2019-10-02 14:31 UTC, sdressler commented on fpga.chart.py
> +# Description: python module to read data from loca FPGAs
Typo: "local"

2019-10-02 14:31 UTC, sdressler commented on fpga.chart.py
> +# Author: Luc Vlaming, Ashley Fraser
Please add me as well, the original version is mine.

2019-10-02 14:46 UTC, afswarm commented on fpga.chart.py
> +# Description: python module to read data from loca FPGAs
That is fixed in the other commit

2019-10-02 14:50 UTC, afswarm commented on fpga.chart.py
> +# Author: Luc Vlaming, Ashley Fraser
Done

2019-10-02 14:51 UTC, afswarm commented
> Sorry, this question just occurred to me: what happens when TEMP cannot be collected, i.e. will it die or just report "0"?



> Sorry, this question just occurred to me: what happens when TEMP cannot be collected, i.e. will it die or just report "0"?

It should report 0

2019-10-02 15:01 UTC, sdressler approved these changes

2019-10-02 15:10 UTC, merged